- name: Install Docker
  gather_facts: yes
  hosts: app
  tasks:
  - name: install docker package on Debian
    when: ansible_facts['os_family'] == "Debian"
    apt:
      name: docker.io
      state: present
  - name: add Docker repo on CentOS
    when: ansible_facts['os_family'] == "RedHat"
    shell: "dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo"
  - name: install Docker on Centos
    dnf:
      name: docker-ce
      state: present
  - name: start Docker
    service:
      name: docker
      state: started
